export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          plan: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          plan?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          plan?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      brands: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          url: string | null;
          description: string | null;
          voice: string | null;
          audience: string | null;
          primary_color: string | null;
          accent_color: string | null;
          voice_profile: Json | null;
          positioning_angles: Json | null;
          vocabulary_guide: Json | null;
          anti_positioning: string | null;
          market_sophistication_level: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          url?: string | null;
          description?: string | null;
          voice?: string | null;
          audience?: string | null;
          primary_color?: string | null;
          accent_color?: string | null;
          voice_profile?: Json | null;
          positioning_angles?: Json | null;
          vocabulary_guide?: Json | null;
          anti_positioning?: string | null;
          market_sophistication_level?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          url?: string | null;
          description?: string | null;
          voice?: string | null;
          audience?: string | null;
          primary_color?: string | null;
          accent_color?: string | null;
          voice_profile?: Json | null;
          positioning_angles?: Json | null;
          vocabulary_guide?: Json | null;
          anti_positioning?: string | null;
          market_sophistication_level?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      competitors: {
        Row: {
          id: string;
          brand_id: string;
          user_id: string;
          name: string;
          website_url: string | null;
          meta_page_id: string | null;
          instagram_handle: string | null;
          twitter_handle: string | null;
          linkedin_url: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          brand_id: string;
          user_id: string;
          name: string;
          website_url?: string | null;
          meta_page_id?: string | null;
          instagram_handle?: string | null;
          twitter_handle?: string | null;
          linkedin_url?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string;
          user_id?: string;
          name?: string;
          website_url?: string | null;
          meta_page_id?: string | null;
          instagram_handle?: string | null;
          twitter_handle?: string | null;
          linkedin_url?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      competitor_ads: {
        Row: {
          id: string;
          competitor_id: string;
          source: string;
          external_id: string | null;
          ad_type: string | null;
          headline: string | null;
          body_text: string | null;
          cta_text: string | null;
          media_urls: string[] | null;
          landing_page_url: string | null;
          engagement_metrics: Json | null;
          is_active: boolean | null;
          first_seen_at: string | null;
          last_seen_at: string | null;
          raw_data: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          competitor_id: string;
          source: string;
          external_id?: string | null;
          ad_type?: string | null;
          headline?: string | null;
          body_text?: string | null;
          cta_text?: string | null;
          media_urls?: string[] | null;
          landing_page_url?: string | null;
          engagement_metrics?: Json | null;
          is_active?: boolean | null;
          first_seen_at?: string | null;
          last_seen_at?: string | null;
          raw_data?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          competitor_id?: string;
          source?: string;
          external_id?: string | null;
          ad_type?: string | null;
          headline?: string | null;
          body_text?: string | null;
          cta_text?: string | null;
          media_urls?: string[] | null;
          landing_page_url?: string | null;
          engagement_metrics?: Json | null;
          is_active?: boolean | null;
          first_seen_at?: string | null;
          last_seen_at?: string | null;
          raw_data?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      competitor_content: {
        Row: {
          id: string;
          competitor_id: string;
          source: string;
          external_id: string | null;
          content_type: string | null;
          title: string | null;
          body_text: string | null;
          media_urls: string[] | null;
          engagement_metrics: Json | null;
          published_at: string | null;
          raw_data: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          competitor_id: string;
          source: string;
          external_id?: string | null;
          content_type?: string | null;
          title?: string | null;
          body_text?: string | null;
          media_urls?: string[] | null;
          engagement_metrics?: Json | null;
          published_at?: string | null;
          raw_data?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          competitor_id?: string;
          source?: string;
          external_id?: string | null;
          content_type?: string | null;
          title?: string | null;
          body_text?: string | null;
          media_urls?: string[] | null;
          engagement_metrics?: Json | null;
          published_at?: string | null;
          raw_data?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      competitor_analyses: {
        Row: {
          id: string;
          brand_id: string;
          analysis_type: string;
          title: string | null;
          summary: string | null;
          patterns: Json | null;
          opportunities: Json | null;
          positioning_gaps: Json | null;
          market_sophistication: number | null;
          winning_patterns: Json | null;
          anti_patterns: Json | null;
          recommendations: Json | null;
          competitor_gap_analysis: Json | null;
          ads_analyzed: number;
          content_analyzed: number;
          raw_response: string | null;
          pipeline_run_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          brand_id: string;
          analysis_type: string;
          title?: string | null;
          summary?: string | null;
          patterns?: Json | null;
          opportunities?: Json | null;
          positioning_gaps?: Json | null;
          market_sophistication?: number | null;
          winning_patterns?: Json | null;
          anti_patterns?: Json | null;
          recommendations?: Json | null;
          competitor_gap_analysis?: Json | null;
          ads_analyzed?: number;
          content_analyzed?: number;
          raw_response?: string | null;
          pipeline_run_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string;
          analysis_type?: string;
          title?: string | null;
          summary?: string | null;
          patterns?: Json | null;
          opportunities?: Json | null;
          positioning_gaps?: Json | null;
          market_sophistication?: number | null;
          winning_patterns?: Json | null;
          anti_patterns?: Json | null;
          recommendations?: Json | null;
          competitor_gap_analysis?: Json | null;
          ads_analyzed?: number;
          content_analyzed?: number;
          raw_response?: string | null;
          pipeline_run_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      generated_creatives: {
        Row: {
          id: string;
          brand_id: string;
          user_id: string;
          analysis_id: string | null;
          platform: string;
          format: string;
          headline: string | null;
          headline_variants: string[] | null;
          primary_text: string | null;
          primary_text_variants: string[] | null;
          description: string | null;
          cta: string | null;
          image_prompt: string | null;
          image_concept_description: string | null;
          suggested_colors: Json | null;
          target_audience: string | null;
          competitive_angle: string | null;
          confidence_score: number | null;
          status: string;
          feedback: string | null;
          pipeline_run_id: string | null;
          positioning_angle_type: string | null;
          positioning_framework: string | null;
          copywriting_framework: string | null;
          schwartz_sophistication_level: number | null;
          psychological_trigger: string | null;
          angle_type: string | null;
          platform_variants: Json | null;
          ab_variants: Json | null;
          image_concepts: Json | null;
          video_script: string | null;
          video_script_concept: string | null;
          google_headlines: string[] | null;
          google_descriptions: string[] | null;
          linkedin_intro_text: string | null;
          linkedin_headline: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          brand_id: string;
          user_id: string;
          analysis_id?: string | null;
          platform: string;
          format: string;
          headline?: string | null;
          headline_variants?: string[] | null;
          primary_text?: string | null;
          primary_text_variants?: string[] | null;
          description?: string | null;
          cta?: string | null;
          image_prompt?: string | null;
          image_concept_description?: string | null;
          suggested_colors?: Json | null;
          target_audience?: string | null;
          competitive_angle?: string | null;
          confidence_score?: number | null;
          status?: string;
          feedback?: string | null;
          pipeline_run_id?: string | null;
          positioning_angle_type?: string | null;
          positioning_framework?: string | null;
          copywriting_framework?: string | null;
          schwartz_sophistication_level?: number | null;
          psychological_trigger?: string | null;
          angle_type?: string | null;
          platform_variants?: Json | null;
          ab_variants?: Json | null;
          image_concepts?: Json | null;
          video_script?: string | null;
          video_script_concept?: string | null;
          google_headlines?: string[] | null;
          google_descriptions?: string[] | null;
          linkedin_intro_text?: string | null;
          linkedin_headline?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string;
          user_id?: string;
          analysis_id?: string | null;
          platform?: string;
          format?: string;
          headline?: string | null;
          headline_variants?: string[] | null;
          primary_text?: string | null;
          primary_text_variants?: string[] | null;
          description?: string | null;
          cta?: string | null;
          image_prompt?: string | null;
          image_concept_description?: string | null;
          suggested_colors?: Json | null;
          target_audience?: string | null;
          competitive_angle?: string | null;
          confidence_score?: number | null;
          status?: string;
          feedback?: string | null;
          pipeline_run_id?: string | null;
          positioning_angle_type?: string | null;
          positioning_framework?: string | null;
          copywriting_framework?: string | null;
          schwartz_sophistication_level?: number | null;
          psychological_trigger?: string | null;
          angle_type?: string | null;
          platform_variants?: Json | null;
          ab_variants?: Json | null;
          image_concepts?: Json | null;
          video_script?: string | null;
          video_script_concept?: string | null;
          google_headlines?: string[] | null;
          google_descriptions?: string[] | null;
          linkedin_intro_text?: string | null;
          linkedin_headline?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      pipeline_runs: {
        Row: {
          id: string;
          brand_id: string | null;
          status: string;
          steps_completed: string[] | null;
          error_log: Json | null;
          meta_ads_found: number;
          social_posts_found: number;
          pages_analyzed: number;
          creatives_generated: number;
          started_at: string;
          completed_at: string | null;
          duration_ms: number | null;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          status?: string;
          steps_completed?: string[] | null;
          error_log?: Json | null;
          meta_ads_found?: number;
          social_posts_found?: number;
          pages_analyzed?: number;
          creatives_generated?: number;
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          status?: string;
          steps_completed?: string[] | null;
          error_log?: Json | null;
          meta_ads_found?: number;
          social_posts_found?: number;
          pages_analyzed?: number;
          creatives_generated?: number;
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
        };
        Relationships: [];
      };
      jobs: {
        Row: {
          id: string;
          brand_id: string | null;
          user_id: string | null;
          job_type: string;
          status: string;
          progress: number;
          progress_message: string | null;
          result: Json | null;
          error: string | null;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
          duration_ms: number | null;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          job_type: string;
          status?: string;
          progress?: number;
          progress_message?: string | null;
          result?: Json | null;
          error?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          duration_ms?: number | null;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          job_type?: string;
          status?: string;
          progress?: number;
          progress_message?: string | null;
          result?: Json | null;
          error?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          duration_ms?: number | null;
        };
        Relationships: [];
      };
      team_members: {
        Row: {
          id: string;
          brand_id: string | null;
          user_id: string | null;
          role: string;
          invited_by: string | null;
          joined_at: string;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          role?: string;
          invited_by?: string | null;
          joined_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          role?: string;
          invited_by?: string | null;
          joined_at?: string;
        };
        Relationships: [];
      };
      team_invites: {
        Row: {
          id: string;
          brand_id: string | null;
          email: string;
          role: string;
          invited_by: string | null;
          status: string;
          created_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          email: string;
          role?: string;
          invited_by?: string | null;
          status?: string;
          created_at?: string;
          expires_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          email?: string;
          role?: string;
          invited_by?: string | null;
          status?: string;
          created_at?: string;
          expires_at?: string;
        };
        Relationships: [];
      };
      social_posts: {
        Row: {
          id: string;
          brand_id: string | null;
          user_id: string | null;
          platform: string;
          post_type: string;
          content: string;
          media_prompts: Json | null;
          media_urls: string[] | null;
          hashtags: string[] | null;
          scheduled_for: string | null;
          published_at: string | null;
          status: string;
          ghl_post_id: string | null;
          source_content_id: string | null;
          engagement_likes: number | null;
          engagement_comments: number | null;
          engagement_shares: number | null;
          engagement_views: number | null;
          competitor_inspiration: Json | null;
          positioning_angle_type: string | null;
          copywriting_framework: string | null;
          feedback: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          platform: string;
          post_type: string;
          content: string;
          media_prompts?: Json | null;
          media_urls?: string[] | null;
          hashtags?: string[] | null;
          scheduled_for?: string | null;
          published_at?: string | null;
          status?: string;
          ghl_post_id?: string | null;
          source_content_id?: string | null;
          engagement_likes?: number | null;
          engagement_comments?: number | null;
          engagement_shares?: number | null;
          engagement_views?: number | null;
          competitor_inspiration?: Json | null;
          positioning_angle_type?: string | null;
          copywriting_framework?: string | null;
          feedback?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          platform?: string;
          post_type?: string;
          content?: string;
          media_prompts?: Json | null;
          media_urls?: string[] | null;
          hashtags?: string[] | null;
          scheduled_for?: string | null;
          published_at?: string | null;
          status?: string;
          ghl_post_id?: string | null;
          source_content_id?: string | null;
          engagement_likes?: number | null;
          engagement_comments?: number | null;
          engagement_shares?: number | null;
          engagement_views?: number | null;
          competitor_inspiration?: Json | null;
          positioning_angle_type?: string | null;
          copywriting_framework?: string | null;
          feedback?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      content_atoms: {
        Row: {
          id: string;
          brand_id: string | null;
          user_id: string | null;
          source_type: string;
          source_title: string | null;
          source_content: string;
          source_url: string | null;
          atoms: Json;
          atom_count: number;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          source_type: string;
          source_title?: string | null;
          source_content: string;
          source_url?: string | null;
          atoms?: Json;
          atom_count?: number;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          source_type?: string;
          source_title?: string | null;
          source_content?: string;
          source_url?: string | null;
          atoms?: Json;
          atom_count?: number;
          status?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      briefings: {
        Row: {
          id: string;
          brand_id: string | null;
          briefing_date: string;
          briefing_type: string;
          executive_summary: string | null;
          health_score: number | null;
          key_metrics: Json | null;
          wins: Json | null;
          concerns: Json | null;
          action_items: Json | null;
          competitor_moves: Json | null;
          content_recommendations: Json | null;
          budget_recommendations: Json | null;
          raw_response: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          briefing_date?: string;
          briefing_type?: string;
          executive_summary?: string | null;
          health_score?: number | null;
          key_metrics?: Json | null;
          wins?: Json | null;
          concerns?: Json | null;
          action_items?: Json | null;
          competitor_moves?: Json | null;
          content_recommendations?: Json | null;
          budget_recommendations?: Json | null;
          raw_response?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          briefing_date?: string;
          briefing_type?: string;
          executive_summary?: string | null;
          health_score?: number | null;
          key_metrics?: Json | null;
          wins?: Json | null;
          concerns?: Json | null;
          action_items?: Json | null;
          competitor_moves?: Json | null;
          content_recommendations?: Json | null;
          budget_recommendations?: Json | null;
          raw_response?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      marketing_calendar: {
        Row: {
          id: string;
          brand_id: string | null;
          date: string;
          event_type: string;
          title: string;
          description: string | null;
          platform: string | null;
          status: string;
          content_id: string | null;
          campaign_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          date: string;
          event_type: string;
          title: string;
          description?: string | null;
          platform?: string | null;
          status?: string;
          content_id?: string | null;
          campaign_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          date?: string;
          event_type?: string;
          title?: string;
          description?: string | null;
          platform?: string | null;
          status?: string;
          content_id?: string | null;
          campaign_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      youtube_channels: {
        Row: {
          id: string;
          competitor_id: string | null;
          brand_id: string | null;
          channel_id: string;
          channel_name: string | null;
          subscriber_count: number | null;
          video_count: number | null;
          view_count: number | null;
          description: string | null;
          thumbnail_url: string | null;
          last_scraped_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          competitor_id?: string | null;
          brand_id?: string | null;
          channel_id: string;
          channel_name?: string | null;
          subscriber_count?: number | null;
          video_count?: number | null;
          view_count?: number | null;
          description?: string | null;
          thumbnail_url?: string | null;
          last_scraped_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          competitor_id?: string | null;
          brand_id?: string | null;
          channel_id?: string;
          channel_name?: string | null;
          subscriber_count?: number | null;
          video_count?: number | null;
          view_count?: number | null;
          description?: string | null;
          thumbnail_url?: string | null;
          last_scraped_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      youtube_videos: {
        Row: {
          id: string;
          channel_id: string | null;
          competitor_id: string | null;
          brand_id: string | null;
          video_id: string;
          title: string | null;
          description: string | null;
          view_count: number | null;
          like_count: number | null;
          comment_count: number | null;
          duration: string | null;
          published_at: string | null;
          thumbnail_url: string | null;
          tags: string[] | null;
          transcript: string | null;
          analysis: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          channel_id?: string | null;
          competitor_id?: string | null;
          brand_id?: string | null;
          video_id: string;
          title?: string | null;
          description?: string | null;
          view_count?: number | null;
          like_count?: number | null;
          comment_count?: number | null;
          duration?: string | null;
          published_at?: string | null;
          thumbnail_url?: string | null;
          tags?: string[] | null;
          transcript?: string | null;
          analysis?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          channel_id?: string | null;
          competitor_id?: string | null;
          brand_id?: string | null;
          video_id?: string;
          title?: string | null;
          description?: string | null;
          view_count?: number | null;
          like_count?: number | null;
          comment_count?: number | null;
          duration?: string | null;
          published_at?: string | null;
          thumbnail_url?: string | null;
          tags?: string[] | null;
          transcript?: string | null;
          analysis?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      ad_accounts: {
        Row: {
          id: string;
          brand_id: string | null;
          user_id: string | null;
          platform: string;
          account_id: string;
          account_name: string | null;
          access_token_encrypted: string | null;
          refresh_token_encrypted: string | null;
          token_expires_at: string | null;
          status: string;
          last_synced_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          platform: string;
          account_id: string;
          account_name?: string | null;
          access_token_encrypted?: string | null;
          refresh_token_encrypted?: string | null;
          token_expires_at?: string | null;
          status?: string;
          last_synced_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          platform?: string;
          account_id?: string;
          account_name?: string | null;
          access_token_encrypted?: string | null;
          refresh_token_encrypted?: string | null;
          token_expires_at?: string | null;
          status?: string;
          last_synced_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      ghl_connections: {
        Row: {
          id: string;
          brand_id: string | null;
          user_id: string | null;
          location_id: string;
          access_token_encrypted: string | null;
          refresh_token_encrypted: string | null;
          token_expires_at: string | null;
          status: string;
          connected_platforms: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          location_id: string;
          access_token_encrypted?: string | null;
          refresh_token_encrypted?: string | null;
          token_expires_at?: string | null;
          status?: string;
          connected_platforms?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          brand_id?: string | null;
          user_id?: string | null;
          location_id?: string;
          access_token_encrypted?: string | null;
          refresh_token_encrypted?: string | null;
          token_expires_at?: string | null;
          status?: string;
          connected_platforms?: string[] | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
